### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by ItssJxstnDe** [MalibuTechTeam/mbt_malisling#8] opened 2023-06-16 16:31 UTC
/holster 0-4 
for EUP to adding to player and using the right positions
holster 0 is to remove the holster

And if you not have any of the holsters so you have holster 0 its pulling the Glock like normal and without the HolsterControls

**Comment by MalibuTechTeam** [comment] 2023-06-19 20:43
Duplicate of #6

**Closed by MalibuTechTeam** 2023-06-19 20:43 UTC
Labels: enhancement
